# docker-compose-monitoring.yml
version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/alerts:/etc/prometheus
      
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
      
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"